package main

func main() {
	// helloWorld()
	// values()
	// constants()
	// for_()
	// ifElse()
	// switch_()
	// arrays()
	// slices()
	// maps_()
	// functions()
	// multipleReturnValues()
	// variadicFunctions()
	// closures()
	// recursion()
	// rangeOverBuiltinTypes()
	// points()
	// stringsAndRunes()
	// structs()
	// methods()
	// interfaces()
	// enums()
	// structEmbedding()
	// # generics()
	// rangeOverIterators()
	// errors_()
	// customErrors()
	// goroutines()
	// channels()
	// channelBuffering()
	// channelSynchronization()
	// channelDirection()
	// select_()
	// timeouts()
	// nonBlockingChannelOperations()
	// closingChannels()
	// rangeOverChannels()
	// timers()
	// tickers()
	// workerPools()
	// waitGroups()
	// rateLimiting()
	// atomicCounters()
	// mutexes()
	// statefulGoroutines()
	// sorting()
	sortingByFunctions()
}
